const UPDATE_TOKEN = "UPDATE_TOKEN";
const UPDATE_USERINFO = "GET_USERINFO";
const SET_BRAND_DATA = "SET_BRAND_DATA";
const ADD_TRESS_DATA = "ADD_TRESS_DATA";
export { UPDATE_TOKEN, UPDATE_USERINFO, SET_BRAND_DATA, ADD_TRESS_DATA };
